# main.py — FastAPI application entry point
#
# THIS FILE:
#   1. Creates the FastAPI app instance
#   2. Creates all database tables on startup (if they don't exist)
#   3. Registers all routers (auth, users, addresses, payments)
#   4. Adds CORS middleware so a browser frontend can call this API
#
# TO RUN:
#   pip install -r requirements.txt
#   uvicorn main:app --reload --port 8000
#
# INTERACTIVE API DOCS (auto-generated by FastAPI):
#   http://localhost:8000/docs   ← Swagger UI — test all endpoints here
#   http://localhost:8000/redoc  ← ReDoc (alternative doc format)

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import RedirectResponse

from database import engine, Base
from routes import auth_routes, user_routes, address_routes, payment_routes

# Create all tables defined in models.py if they don't already exist.
# Safe to call on every startup — it's a no-op if tables are already there.
Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="E-Commerce — User Management API",
    description=(
        "Handles user registration, login (JWT), profile management, "
        "address book, and saved payment methods."
    ),
    version="1.0.0",
)

# CORS — allows the Streamlit UI (or any browser app) to call this API.
# In production: replace allow_origins=["*"] with your actual domain(s).
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Register routers — each router owns a group of related endpoints
app.include_router(auth_routes.router)     # /auth/*
app.include_router(user_routes.router)     # /users/me
app.include_router(address_routes.router)  # /users/me/addresses
app.include_router(payment_routes.router)  # /users/me/payment-methods


@app.get("/", include_in_schema=False)
def root():
    """Redirect browser visits at / to the Swagger UI."""
    return RedirectResponse(url="/docs")


@app.get("/health", tags=["System"])
def health_check():
    """Simple liveness check — useful for Docker/k8s health probes."""
    return {"status": "ok"}
