"""
Local model fallback for the RAG Shopping Assistant.

Activated when Azure OpenAI is unavailable (timeout, 429, circuit breaker open).

Two fallback tiers:
  Tier 1 — Flan-T5-base (local CPU inference):
      Generates a short natural-language reply from retrieved product context.
      Quality is lower than GPT-5.4-mini but functional.
      Model loaded once at module import time (avoids cold start per request).

  Tier 2 — Keyword-only search result formatting:
      Used when vector indexing itself fails (no embeddings available).
      Returns a structured plain-text list of products without LLM generation.

Usage in rag.py:
    from local_fallback import generate_reply_local, format_keyword_results

    try:
        reply = generate_reply(history, context, message)   # Azure GPT
    except (openai.APITimeoutError, openai.APIConnectionError):
        reply = generate_reply_local(context, message)      # Flan-T5 fallback
"""

from __future__ import annotations

import logging
import os
from typing import Optional

logger = logging.getLogger(__name__)

# ── Lazy model loader ──────────────────────────────────────────────────────────

_pipeline = None          # transformers pipeline (loaded once at startup)
_load_error: Optional[str] = None


def _load_model() -> bool:
    """Load Flan-T5-base once. Returns True on success, False if unavailable."""
    global _pipeline, _load_error
    if _pipeline is not None:
        return True
    if _load_error is not None:
        return False

    if os.getenv("DISABLE_LOCAL_FALLBACK", "").lower() in ("1", "true", "yes"):
        _load_error = "DISABLE_LOCAL_FALLBACK=true"
        logger.info("local_fallback: disabled via env var")
        return False

    try:
        from transformers import pipeline as hf_pipeline  # type: ignore

        logger.info("local_fallback: loading google/flan-t5-base (CPU)…")
        _pipeline = hf_pipeline(
            "text2text-generation",
            model="google/flan-t5-base",
            device=-1,          # CPU
            max_new_tokens=256,
        )
        logger.info("local_fallback: flan-t5-base loaded successfully")
        return True
    except ImportError:
        _load_error = "transformers not installed"
        logger.warning("local_fallback: transformers package not installed — tier-2 only")
        return False
    except Exception as exc:
        _load_error = str(exc)
        logger.warning("local_fallback: model load failed: %s — tier-2 only", exc)
        return False


# Trigger model load at import time so it is warm when first needed.
# This is intentionally done at module-level (startup), not per-request.
_load_model()


# ── Tier 1: Flan-T5 generation ─────────────────────────────────────────────────

_FLAN_PROMPT_TEMPLATE = """\
You are a shopping assistant. Answer the customer's question using only the products listed below.

Products:
{context}

Customer question: {question}

Short helpful answer:"""


def generate_reply_local(context: str, user_message: str) -> str:
    """
    Generate a shopping assistant reply using local Flan-T5-base.

    Returns a short, product-grounded reply. Falls back to format_products_as_text
    if the model is unavailable.

    The response includes a disclaimer that it is generated locally (lower quality).
    """
    if _pipeline is None:
        logger.warning("local_fallback: flan-t5 unavailable, using tier-2 text fallback")
        return _format_products_as_text(context, user_message)

    prompt = _FLAN_PROMPT_TEMPLATE.format(
        context=context[:1500],     # Flan-T5-base has 512 token limit; truncate safely
        question=user_message[:200],
    )
    try:
        outputs = _pipeline(prompt, max_new_tokens=200, do_sample=False)
        generated = outputs[0]["generated_text"].strip()
        return (
            f"{generated}\n\n"
            "_Note: AI service is temporarily unavailable. "
            "This response was generated by a local model and may have lower quality._"
        )
    except Exception as exc:
        logger.error("local_fallback: flan-t5 inference failed: %s", exc)
        return _format_products_as_text(context, user_message)


# ── Tier 2: Keyword-only plain-text formatter ──────────────────────────────────

def format_keyword_results(products: list) -> str:
    """
    Format a list of Product ORM objects as a plain-text shopping response.

    Used when vector indexing fails (no embeddings) — returns raw search results
    without any LLM generation.

    Args:
        products: list of Product ORM instances (from keyword search)

    Returns:
        Plain-text formatted product list with disclaimer.
    """
    if not products:
        return (
            "I could not find products matching your query right now. "
            "Please try again shortly or refine your search terms.\n\n"
            "_AI features are temporarily unavailable._"
        )

    lines = ["Here are the most relevant products I found:\n"]
    for i, p in enumerate(products[:5], 1):
        eff_price = round(p.price * (1 - p.discount_pct / 100), 2)
        stock_note = f"In stock ({p.inventory_count} units)" if p.inventory_count > 0 else "Out of stock"
        lines.append(
            f"{i}. **{p.name}** — ₹{eff_price:,.0f}  |  {p.brand}  |  "
            f"Rating: {p.rating_avg}/5  |  {stock_note}"
        )

    lines.append(
        "\n_Note: AI service is temporarily unavailable. "
        "Showing keyword search results without AI recommendations._"
    )
    return "\n".join(lines)


def _format_products_as_text(context: str, user_message: str) -> str:
    """Extract product names from the pre-built context string as a last resort."""
    lines = ["Based on your query, here are some relevant products:\n"]
    for line in context.split("\n"):
        if line.strip().startswith("[") and "]" in line:
            lines.append(f"• {line.strip()}")
    if len(lines) == 1:
        lines.append("I found some products matching your search but could not load details.")
    lines.append(
        "\n_Note: AI service is temporarily unavailable. "
        "Results shown without personalised recommendations._"
    )
    return "\n".join(lines)


# ── Health check ──────────────────────────────────────────────────────────────

def fallback_status() -> dict:
    """Return the current state of the local fallback for health checks."""
    return {
        "flan_t5_loaded": _pipeline is not None,
        "flan_t5_error": _load_error,
        "tier1_available": _pipeline is not None,
        "tier2_available": True,    # Always available (pure Python formatting)
    }
